# STAGE 1 — BUILD NATIVE IMAGE
FROM ghcr.io/graalvm/graalvm-community:21 AS builder

WORKDIR /app

RUN chmod +x /usr/share/bin/gu
RUN gu install native-image

COPY . .

RUN ./gradlew clean nativeCompile --no-daemon

# STAGE 2 — RUNTIME ALPINE
FROM alpine:3.20 AS runtime

RUN apk add --no-cache ca-certificates

WORKDIR /app

COPY --from=builder /app/build/native/nativeCompile/fitclass app

RUN chmod +x app

EXPOSE 8080

ENTRYPOINT ["./app"]

